spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmarkit
    username: app
    password: ybigta4321
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 5672
    username: mq
    password: secret

security:
  enable: true
